export const SECTIONS = {
    MAIN: 'SECTION_MAIN',
    SEARCH: 'SECTION_SEARCH',
    FRIENDS: 'SECTION_FRIENDS',
    NOTIFICATIONS: 'SECTION_NOTIFICATIONS',
};

export const ACTIONS = {
    SET_NOTIFICATIONS: 'HME_SET_NOTIFICATIONS',
};