import { API_URL } from '../app/constants';

export const SECTIONS = {
    MAIN: 'SECTION_MAIN',
    SEARCH: 'SECTION_SEARCH',
    FRIENDS: 'SECTION_FRIENDS',
    NOTIFICATIONS: 'SECTION_NOTIFICATIONS',
};

export const ACTIONS = {
    SET_NOTIFICATIONS: 'HME_SET_NOTIFICATIONS',
    DEL_NOTIFICATION: 'HME_DEL_NOTIFICATION',
    SET_SEARCH_RESULTS: 'HME_SET_SEARCH_RESULTS',
    SET_SEARCHBAR_RESULTS: 'HME_SET_SEARCHBAR_RESULTS',
};

export const ROUTES = {
    GET_NOTIFICATIONS: `${API_URL}/notifications/`,
    DEL_NOTIFICATION: (id) => `${API_URL}/notifications/${id}/`,
    SEARCH_USERS: `${API_URL}/users/search`
};